const CAPACITY = 50;
const TAKEAWAY_CAPACITY = 10;
const TIME_PER_DINE = 30;
const HERE = 1;
const TO_GO = 2;
const ALL = 3;

module.exports = {
  API_TOKEN: API_TOKEN,
  CAPACITY: CAPACITY,
  TAKEAWAY_CAPACITY: TAKEAWAY_CAPACITY,
  TIME_PER_DINE: TIME_PER_DINE,
  HERE: HERE,
  TO_GO: TO_GO,
  ALL: ALL
};
